interface GeminiPart {
  text: string
}

interface GeminiContent {
  role?: string
  parts: GeminiPart[]
}

interface GeminiGenerationConfig {
  maxOutputTokens?: number
  responseMimeType?: string
}

interface GeminiSystemInstruction {
  parts: GeminiPart[]
}

interface GeminiPayload {
  contents: GeminiContent[]
  generationConfig?: GeminiGenerationConfig
  systemInstruction?: GeminiSystemInstruction
}

export async function callGemini(
  prompt: string,
  responseJson: boolean = false,
  maxTokens: number = 300
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey || apiKey === 'your_gemini_api_key_here' || apiKey === 'placeholder') {
    throw new Error('Gemini API key is not configured')
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`
  const payload: GeminiPayload = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      maxOutputTokens: maxTokens,
    }
  }

  if (responseJson && payload.generationConfig) {
    payload.generationConfig.responseMimeType = "application/json"
  }

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  })

  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Gemini API error: ${res.statusText} - ${errText}`)
  }

  const data = await res.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text
  if (!text) {
    throw new Error('No content generated by Gemini')
  }
  return text.trim()
}

export async function callGeminiChat(
  messages: { role: string; content: string }[],
  systemInstruction?: string,
  maxTokens: number = 400
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey || apiKey === 'your_gemini_api_key_here' || apiKey === 'placeholder') {
    throw new Error('Gemini API key is not configured')
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`

  // Map messages to Gemini's user/model role expectations
  const contents: GeminiContent[] = messages.map(m => ({
    role: m.role === 'assistant' ? 'model' : 'user',
    parts: [{ text: m.content }]
  }))

  const payload: GeminiPayload = {
    contents,
    generationConfig: {
      maxOutputTokens: maxTokens,
    }
  }

  if (systemInstruction) {
    payload.systemInstruction = {
      parts: [{ text: systemInstruction }]
    }
  }

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  })

  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Gemini API error: ${res.statusText} - ${errText}`)
  }

  const data = await res.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text
  if (!text) {
    throw new Error('No content generated by Gemini')
  }
  return text.trim()
}
