import { NextResponse } from 'next/server'

async function callGemini(prompt: string, responseJson: boolean = false, maxTokens: number = 300): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey || apiKey === 'your_gemini_api_key_here' || apiKey === 'placeholder') {
    throw new Error('Gemini API key is not configured')
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`
  const payload: any = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      maxOutputTokens: maxTokens,
    }
  }

  if (responseJson) {
    payload.generationConfig.responseMimeType = "application/json"
  }

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  })

  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Gemini API error: ${res.statusText} - ${errText}`)
  }

  const data = await res.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text
  if (!text) {
    throw new Error('No content generated by Gemini')
  }
  return text.trim()
}

const PYTHON_API_URL = process.env.PYTHON_API_URL || 'http://localhost:8000'

export async function GET(
  request: Request,
  { params }: { params: Promise<{ feature: string }> }
) {
  const { feature } = await params

  if (feature === 'regime') {
    try {
      const res = await fetch(`${PYTHON_API_URL}/regime`)
      if (res.ok) {
        const data = await res.json()
        return NextResponse.json(data)
      }
    } catch {
      // Offline fallback
    }

    return NextResponse.json({
      regime: 'ranging',
      recommended_strategy: 'fvg_scalper',
      rationale: 'XAUUSD is consolidating within a tight range of $1945 - $1960. Average True Range is contracting and volume indicators show balanced distributions.'
    })
  }

  if (feature === 'context') {
    return NextResponse.json({
      selectedPair: 'XAUUSD',
      activeStrategy: 'ema_crossover',
      openPositionsCount: 2,
      dailyPnl: -45.50,
      regime: 'trending_bull',
      rsi: 42.5,
      atr: 2.4,
      bridgeStatus: 'connected'
    })
  }

  return NextResponse.json({ error: 'Not Found' }, { status: 404 })
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ feature: string }> }
) {
  const { feature } = await params

  try {
    const body = await request.json()

    if (feature === 'analyze-backtest') {
      const results = body.results || {}
      
      if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== 'your_gemini_api_key_here' && process.env.GEMINI_API_KEY !== 'placeholder') {
        try {
          const prompt = `Analyze this backtest report and explain strengths and weaknesses in under 100 words:
Strategy: ${results.strategy}
Net Profit: $${results.net_pnl}
Win Rate: ${results.win_rate}%
Profit Factor: ${results.profit_factor}
Max Drawdown: ${results.max_drawdown_pct}%
Total Trades: ${results.total_trades}`

          const text = await callGemini(prompt, false, 200)
          return NextResponse.json({ analysis: text })
        } catch (err) {
          console.error("Gemini backtest analysis failed:", err)
        }
      }

      return NextResponse.json({
        analysis: "The strategy shows highly consistent equity growth. Win rate at " + (results.win_rate || 64) + "% is solid, and drawdown is held in tight bounds under " + (results.max_drawdown_pct || 5) + "%. Recommendation is to initiate forward-testing on demo account."
      })
    }

    if (feature === 'build-strategy') {
      const description = body.description || ''
      let config = {
        htf: "H1",
        ltf: "M5",
        swing_length: 15,
        ob_enabled: true,
        fvg_enabled: false,
        liquidity_enabled: true,
        sessions: ["London"],
        min_rr: 2.0,
        trailing_start_rr: 1.0,
        break_even_after_rr: 1.0,
        tp_levels: [{ rr: 1.5, close_pct: 50 }, { rr: 3.0, close_pct: 50 }]
      }

      if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== 'your_gemini_api_key_here' && process.env.GEMINI_API_KEY !== 'placeholder') {
        try {
          const prompt = `Generate a JSON strategy configuration based on this description: "${description}"
Format your response ONLY as a JSON object matching this structure:
{
  "htf": "H4" or "H1" or "M30",
  "ltf": "M15" or "M5" or "M1",
  "swing_length": number between 5 and 50,
  "ob_enabled": boolean,
  "fvg_enabled": boolean,
  "liquidity_enabled": boolean,
  "sessions": array containing subsets of ["London", "New York", "Asia"],
  "min_rr": float between 0.5 and 5.0,
  "trailing_start_rr": float,
  "break_even_after_rr": float,
  "tp_levels": [{"rr": float, "close_pct": integer}]
}`

          const text = await callGemini(prompt, true, 300)
          config = JSON.parse(text)
        } catch (err) {
          console.warn("Gemini failed to generate strategy configuration, using fallback presets:", err)
        }
      }

      return NextResponse.json({
        name: 'ai_custom_strategy',
        preview: 'AI-Custom Scalper Profile',
        config
      })
    }

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Execution error'
    return NextResponse.json({ error: message }, { status: 500 })
  }

  return NextResponse.json({ error: 'Not Found' }, { status: 404 })
}
