import { NextResponse } from 'next/server'
import { createClient } from 'redis'
import { getSupabaseServerClient, getCurrentUserId } from '@/lib/supabase-server'

const REDIS_URL = process.env.REDIS_URL || 'redis://127.0.0.1:6379'
import { getPythonApiUrl } from '@/lib/api-helper'

async function callGemini(prompt: string, responseJson: boolean = false, maxTokens: number = 300): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey || apiKey === 'your_gemini_api_key_here' || apiKey === 'placeholder') {
    throw new Error('Gemini API key is not configured')
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`
  const payload: any = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      maxOutputTokens: maxTokens,
    }
  }

  if (responseJson) {
    payload.generationConfig.responseMimeType = "application/json"
  }

  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  })

  if (!res.ok) {
    const errText = await res.text()
    throw new Error(`Gemini API error: ${res.statusText} - ${errText}`)
  }

  const data = await res.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text
  if (!text) {
    throw new Error('No content generated by Gemini')
  }
  return text.trim()
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ feature: string }> }
) {
  const { feature } = await params

  if (feature === 'regime') {
    try {
      const userId = await getCurrentUserId()
      const pythonApiUrl = await getPythonApiUrl(userId || undefined)
      const res = await fetch(`${pythonApiUrl}/regime`, {
        headers: { 'ngrok-skip-browser-warning': 'any-value' }
      })
      if (!res.ok) {
        throw new Error(`FastAPI backend responded with status ${res.status}`)
      }
      const data = await res.json()
      return NextResponse.json(data)
    } catch (err: any) {
      return NextResponse.json({ error: err.message || 'FastAPI execution engine is offline' }, { status: 502 })
    }
  }

  if (feature === 'context') {
    const userId = await getCurrentUserId()
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    try {
      const supabase = getSupabaseServerClient()
      const redis = createClient({ url: REDIS_URL })
      await redis.connect()

      // Get open positions count
      const positionsData = await redis.get(`positions:${userId}`)
      const positions = positionsData ? JSON.parse(positionsData) : []
      const openPositionsCount = positions.length

      // Get daily P&L from trades
      const startOfDay = new Date()
      startOfDay.setHours(0,0,0,0)
      const { data: todayTrades, error: dbError } = await supabase
        .from('trades')
        .select('pnl_usd')
        .eq('user_id', userId)
        .gte('opened_at', startOfDay.toISOString())

      if (dbError) throw dbError

      const dailyPnl = (todayTrades || []).reduce((s, t) => s + (t.pnl_usd ?? 0), 0)

      // Get bridge status
      const bridgeStatusKey = await redis.get(`bridge:status:${userId}`)
      const bridgeStatus = bridgeStatusKey ? 'connected' : 'disconnected'

      await redis.disconnect()

      // Fetch regime from FastAPI
      let regime = 'ranging'
      try {
        const pythonApiUrl = await getPythonApiUrl(userId)
        const regimeRes = await fetch(`${pythonApiUrl}/regime`, {
          headers: { 'ngrok-skip-browser-warning': 'any-value' }
        })
        if (regimeRes.ok) {
          const regimeData = await regimeRes.json()
          regime = regimeData.regime
        }
      } catch {}

      return NextResponse.json({
        selectedPair: 'XAUUSD',
        activeStrategy: 'ema_crossover',
        openPositionsCount,
        dailyPnl,
        regime,
        rsi: 42.5,
        atr: 2.4,
        bridgeStatus
      })
    } catch (err: any) {
      return NextResponse.json({ error: err.message || 'Failed to retrieve live connection context' }, { status: 500 })
    }
  }

  return NextResponse.json({ error: 'Not Found' }, { status: 404 })
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ feature: string }> }
) {
  const { feature } = await params

  try {
    const body = await request.json()

    if (feature === 'analyze-backtest') {
      const results = body.results || {}
      
      if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_gemini_api_key_here' || process.env.GEMINI_API_KEY === 'placeholder') {
        return NextResponse.json({ error: 'Google Gemini API key is not configured. Live AI advisor is required.' }, { status: 400 })
      }

      try {
        const prompt = `Analyze this backtest report and explain strengths and weaknesses in under 100 words:
Strategy: ${results.strategy}
Net Profit: $${results.net_pnl}
Win Rate: ${results.win_rate}%
Profit Factor: ${results.profit_factor}
Max Drawdown: ${results.max_drawdown_pct}%
Total Trades: ${results.total_trades}`

        const text = await callGemini(prompt, false, 200)
        return NextResponse.json({ analysis: text })
      } catch (err: any) {
        return NextResponse.json({ error: `Gemini call failed: ${err.message}` }, { status: 502 })
      }
    }

    if (feature === 'build-strategy') {
      const description = body.description || ''
      
      if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'your_gemini_api_key_here' || process.env.GEMINI_API_KEY === 'placeholder') {
        return NextResponse.json({ error: 'Google Gemini API key is not configured. Live AI advisor is required.' }, { status: 400 })
      }

      try {
        const prompt = `Generate a JSON strategy configuration based on this description: "${description}"
Format your response ONLY as a JSON object matching this structure:
{
  "htf": "H4" or "H1" or "M30",
  "ltf": "M15" or "M5" or "M1",
  "swing_length": number between 5 and 50,
  "ob_enabled": boolean,
  "fvg_enabled": boolean,
  "liquidity_enabled": boolean,
  "sessions": array containing subsets of ["London", "New York", "Asia"],
  "min_rr": float between 0.5 and 5.0,
  "trailing_start_rr": float,
  "break_even_after_rr": float,
  "tp_levels": [{"rr": float, "close_pct": integer}]
}`

        const text = await callGemini(prompt, true, 300)
        const config = JSON.parse(text)
        return NextResponse.json({
          name: 'ai_custom_strategy',
          preview: 'AI-Custom Scalper Profile',
          config
        })
      } catch (err: any) {
        return NextResponse.json({ error: `Failed to compile strategy config: ${err.message}` }, { status: 502 })
      }
    }

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Execution error'
    return NextResponse.json({ error: message }, { status: 500 })
  }

  return NextResponse.json({ error: 'Not Found' }, { status: 404 })
}
